### ISSUE TITLE
convert .pdb file to .crd file 

### ISSUE THREAD

**Issue by MamtaMohan** [rmcgibbo/mixtape-scripts#1]
Hello,

I want to convert .pdb file to .crd file.

Can this software do that.

Mamta

**Comment by rmcgibbo** [comment]
No.

**Comment by MamtaMohan** [comment]
Thank you.

Mamta

**Comment by rmcgibbo** [comment]
The library I would use for this is mdtraj.

**Comment by MamtaMohan** [comment]
Dear Robert,

Thank you for your help.

MDTraj does not do conversion from .pdb to .crd file.

Mamta

**Comment by rmcgibbo** [comment]
Well, perhaps cpptraj then.

**Comment by MamtaMohan** [comment]
Thank you Robert.

I will try that.

There is also Bio3D wil does that. It is in R (I do not know R) so I am looking package in python first if nothing works than I may try that.

I thought you may like to know about Bio3D

Mamta
